### PR TITLE
Implement participation filter

### PR DESCRIPTION
**Pull request by alexduf**
I'm going to test it on my machine for few days / weeks before merging.

This only count notification if you've been participating to the PR / bug. I'm not sure how github defines "participation" but if I find a good definition I'll include it in the settings otherwise it's a bit unclear what the option is for.

### CODE REVIEW

**Comment by salmanulfarzy** [comment]
This looks good and working as expected.

Quick request, Could you point me towards the importance of schema and how it was compiled ? May be I'm looking in the wrong place, But Gnome shell extensions doc looks very scattered and limited.

**Comment by alexduf** [comment]
>Quick request, Could you point me towards the importance of schema and how it was compiled ?
I use glib-compile-schemas
https://www.systutorials.com/docs/linux/man/1-glib-compile-schemas/

It's not very clear why, but it seems like gnome needs its prefs stored in that specific format. The compiled results is generated from the file in `schemas/org.gnome.shell.extensions.github.notifications.gschema.xml`

>May be I'm looking in the wrong place, But Gnome shell extensions doc looks very scattered and limited.

No I've got the same problem. I've only learned by trial and error and spent way too much time to make the 300 lines of this extension work. I think gnome needs to step up their game regarding extension documentation and the developer experience. You currently have to restart your desktop when you update an extension which I find absolutely crazy.

What I try to do is find the GTK documentation and try to guess how it's been translated to javascript. For instance for the HTTP library (Soup) I got most of my information here https://developer.gnome.org/libsoup/stable/ and then tried to guess how it was implemented or bound in javascript. It's painful to do but if you're patient and determined (and quite frankly lucky enough in your google searches) then maybe you get something running.

Sorry I'll stop ranting now :D

**Comment by salmanulfarzy** [comment]
> I use glib-compile-schemas

Thank you @alexduf That's very helpful :+1: 

As it turns out Gnome keeps compiles the `*.gschema.xml` files into binary files to keep the startup time low, Where GSettings defined inside XML files store values as GValues.

Looking forward to work on improving Gnome shell extensions documentation someday soon :)

**Some relevant links**

- https://developer.gnome.org/gio/2.58/glib-compile-schemas.html
- https://developer.gnome.org/gio/2.58/GSettings.html

**Comment by alexduf** [comment]
Submitted for review today

**Pull request merged**
