### PR TITLE
Support gnome 40 (the bare minimum)

### LINKED ISSUE #32: Support for Gnome 40
The most recent version of the extension doesn't work with the latest version of Gnome.

I'm no JS/Gnome developer so I'm afraid I can't help out with writing code, but please let me know if I can help out with testing or something else.

### PR DESCRIPTION
**Pull request by machitgarha**
The bare minimum to support Gnome 40. This means, for example, there still are UI inconsistencies, but the main functionality seems to be OK. Should close #32.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@alexduf this would be amazing to have! I've been missing this extension

**Comment by Shelvak** [comment]
Awesome Mohammad, thanks for that. I can confirm that the PR is working. Before the extension worked for me but I can't open the config. :+1:

**Comment by JacobCallahan** [comment]
Ping on this getting merged

**Comment by egormanga** [comment]
@JacobCallahan, just turn on the notifications for the PR on the GitHub itself:
image

**Comment by JacobCallahan** [comment]
> @JacobCallahan, just turn on the notifications for the PR on the GitHub itself:
> image
> 

I'm asking for an update on this pr getting merged from the maintainers, not how to subscribe to notifications in general 😉

**Comment by egormanga** [comment]
@JacobCallahan that's what I'm saying: why bother the maintainers when you can get an absolutely equivalent notification but automated — that is exactly the function of this setting (in the right menu of the issue).

**Comment by JacobCallahan** [comment]
> @JacobCallahan that's what I'm saying: why bother the maintainers when you can get an absolutely equivalent notification but automated — that is exactly the function of this setting (in the right menu of the issue).

You're misunderstanding me. I am not interested in simply getting notifications on this issue. I am pinging this issue in hopes that the maintainers will see it and tell us if/when they will merge it.

**Comment by egormanga** [comment]
> I am pinging this issue

Well, one might think (and I did) that you are requesting to ping _you_ as soon as the PR will be merged upstream. Please be more clear in your wordings. What you did is called a 'bump', not 'ping', and considered bad practice.

Also, the maintainers will merge it as soon as they will. If you are wanting to help speed up this process, you can positive review («approve») the code (or rule out the issues, instead), or do some testing, including writing unit tests — this applies to all OSS projects in general, yet not particularly well to this extension.

**Comment by bherrin3** [comment]
Ping this as well! LGTM!

**Comment by machitgarha** [comment]
@alexduf, it's going to be three months waiting for this to get merged. People are waiting for this. Could you please have a look?

**Comment by alexduf** [comment]
Ha, incredible, thanks everyone. Apologies I've been on leave for quite a while. I'll merge, package and submit.

You're all amazing 😄

**Comment by alexduf** [comment]
It's submitted to extensions.gnome.org, note that I am not in a position to test it!

**Comment by machitgarha** [comment]
@alexduf Great! Special thanks for your attention. :)

**Comment by alexduf** [comment]
Ha, I've had to deactivate version 18 because it wasn't backward compatible with gnome versions under 3.40

Before we get this extension working with gnome 40 we need:
 - to address comments that have been raised during the code review of the extension by the gnome folks: https://github.com/alexduf/gnome-github-notifications/issues/34
 - to remove older versions from the `metadata.json` file: https://github.com/alexduf/gnome-github-notifications/issues/35 such that older versions of gnome get pinned to version 17 of the extension, but newer versions of gnome get the updates (at least that how I think it works :crossed_fingers: )

If there are volunteers, do feel free to raise PRs, make sure you mention you intend to work on it on the respective bugs so people don't duplicate the effort.

As always, thank you to all of you for being such fantastic volunteers

**Comment by machitgarha** [comment]
@alexduf

Changes are ready to be merged in #34 and #35.

P.S: There are still UI inconsistencies, but the general functionality should be OK.

**Comment by alexduf** [comment]
I've merged #41 and #42, I've spotted an small error in the imports which I've just fixed on master ff99ba35eea6d87bf4577201ff6dab9682f5a19a

The extension is now back in review! (🤞 )

Thank you again, @machitgarha and thanks everyone for your patience and general enthusiasm!

**Pull request merged**
